package lf;

import java.util.Set;
import kotlin.collections.ArraysKt;
import kotlin.text.Regex;

/* loaded from: classes2.dex */
public abstract class w {
    public static final Ne.f alpha;
    public static final Ne.f bravo;
    public static final Ne.f charlie;
    public static final Ne.f delta;
    public static final Ne.f echo;
    public static final Ne.f foxtrot;
    public static final Ne.f golf;
    public static final Ne.f hotel;
    public static final Ne.f india;
    public static final Ne.f juliet;
    public static final Ne.f kilo;
    public static final Ne.f lima;
    public static final Regex mike;
    public static final Ne.f november;
    public static final Ne.f oscar;
    public static final Ne.f papa;
    public static final Ne.f quebec;
    public static final Set romeo;
    public static final Set sierra;
    public static final Set tango;

    static {
        Ne.f echo2 = Ne.f.echo("getValue");
        alpha = echo2;
        Ne.f echo3 = Ne.f.echo("setValue");
        bravo = echo3;
        Ne.f echo4 = Ne.f.echo("provideDelegate");
        charlie = echo4;
        Ne.f echo5 = Ne.f.echo("equals");
        delta = echo5;
        Ne.f.echo("hashCode");
        Ne.f echo6 = Ne.f.echo("compareTo");
        echo = echo6;
        Ne.f echo7 = Ne.f.echo("contains");
        foxtrot = echo7;
        golf = Ne.f.echo("invoke");
        hotel = Ne.f.echo("iterator");
        india = Ne.f.echo("get");
        juliet = Ne.f.echo("set");
        kilo = Ne.f.echo("next");
        lima = Ne.f.echo("hasNext");
        Ne.f.echo("toString");
        mike = new Regex("component\\d+");
        Ne.f echo8 = Ne.f.echo("and");
        Ne.f echo9 = Ne.f.echo("or");
        Ne.f echo10 = Ne.f.echo("xor");
        Ne.f echo11 = Ne.f.echo("inv");
        Ne.f echo12 = Ne.f.echo("shl");
        Ne.f echo13 = Ne.f.echo("shr");
        Ne.f echo14 = Ne.f.echo("ushr");
        Ne.f echo15 = Ne.f.echo("inc");
        november = echo15;
        Ne.f echo16 = Ne.f.echo("dec");
        oscar = echo16;
        Ne.f echo17 = Ne.f.echo("plus");
        Ne.f echo18 = Ne.f.echo("minus");
        Ne.f echo19 = Ne.f.echo("not");
        Ne.f echo20 = Ne.f.echo("unaryMinus");
        Ne.f echo21 = Ne.f.echo("unaryPlus");
        Ne.f echo22 = Ne.f.echo("times");
        Ne.f echo23 = Ne.f.echo("div");
        Ne.f echo24 = Ne.f.echo("mod");
        Ne.f echo25 = Ne.f.echo("rem");
        Ne.f echo26 = Ne.f.echo("rangeTo");
        papa = echo26;
        Ne.f echo27 = Ne.f.echo("rangeUntil");
        quebec = echo27;
        Ne.f echo28 = Ne.f.echo("timesAssign");
        Ne.f echo29 = Ne.f.echo("divAssign");
        Ne.f echo30 = Ne.f.echo("modAssign");
        Ne.f echo31 = Ne.f.echo("remAssign");
        Ne.f echo32 = Ne.f.echo("plusAssign");
        Ne.f echo33 = Ne.f.echo("minusAssign");
        ArraysKt.g(new Ne.f[]{echo15, echo16, echo21, echo20, echo19, echo11});
        romeo = ArraysKt.g(new Ne.f[]{echo21, echo20, echo19, echo11});
        Set g2 = ArraysKt.g(new Ne.f[]{echo22, echo17, echo18, echo23, echo24, echo25, echo26, echo27});
        sierra = g2;
        kotlin.collections.ab.mike(kotlin.collections.ab.mike(g2, ArraysKt.g(new Ne.f[]{echo8, echo9, echo10, echo11, echo12, echo13, echo14})), ArraysKt.g(new Ne.f[]{echo5, echo7, echo6}));
        tango = ArraysKt.g(new Ne.f[]{echo28, echo29, echo30, echo31, echo32, echo33});
        ArraysKt.g(new Ne.f[]{echo2, echo3, echo4});
    }
}
