package F;

import a0.C0366t;

/* loaded from: classes3.dex */
public final class O {
    public final long alpha;
    public final long amber;
    public final long azure;
    public final long beige;
    public final long black;
    public final long blue;
    public final long bravo;
    public final long bronze;
    public final long charlie;
    public final long coral;
    public final long crimson;
    public final long cyan;
    public final long delta;
    public final long echo;
    public final long emerald;
    public final long foxtrot;
    public ak fuchsia;
    public ak gold;
    public final long golf;
    public ak gray;
    public at green;
    public final long hotel;
    public final long india;
    public T1 indigo;
    public M2 ivory;
    public M2 jade;
    public final long juliet;
    public final long kilo;
    public ay lavender;
    public final long lima;
    public C0129l0 lime;
    public C0156s0 magenta;
    public H1 maroon;
    public final long mike;
    public C0143o2 navy;
    public final long november;
    public C0143o2 ochre;
    public final long oscar;
    public final long papa;
    public final long quebec;
    public final long romeo;
    public final long sierra;
    public final long tango;
    public final long uniform;
    public final long victor;
    public final long whiskey;
    public final long xray;
    public final long yankee;
    public final long zulu;

    public O(long j5, long j6, long j7, long j10, long j11, long j12, long j13, long j14, long j15, long j16, long j17, long j18, long j19, long j20, long j21, long j22, long j23, long j24, long j25, long j26, long j27, long j28, long j29, long j30, long j31, long j32, long j33, long j34, long j35, long j36, long j37, long j38, long j39, long j40, long j41, long j42) {
        this.alpha = j5;
        this.bravo = j6;
        this.charlie = j7;
        this.delta = j10;
        this.echo = j11;
        this.foxtrot = j12;
        this.golf = j13;
        this.hotel = j14;
        this.india = j15;
        this.juliet = j16;
        this.kilo = j17;
        this.lima = j18;
        this.mike = j19;
        this.november = j20;
        this.oscar = j21;
        this.papa = j22;
        this.quebec = j23;
        this.romeo = j24;
        this.sierra = j25;
        this.tango = j26;
        this.uniform = j27;
        this.victor = j28;
        this.whiskey = j29;
        this.xray = j30;
        this.yankee = j31;
        this.zulu = j32;
        this.amber = j33;
        this.azure = j34;
        this.beige = j35;
        this.black = j36;
        this.blue = j37;
        this.bronze = j38;
        this.coral = j39;
        this.crimson = j40;
        this.cyan = j41;
        this.emerald = j42;
    }

    public final String toString() {
        StringBuilder sb2 = new StringBuilder("ColorScheme(primary=");
        ao.ad.bronze(this.alpha, "onPrimary=", sb2);
        ao.ad.bronze(this.bravo, "primaryContainer=", sb2);
        ao.ad.bronze(this.charlie, "onPrimaryContainer=", sb2);
        ao.ad.bronze(this.delta, "inversePrimary=", sb2);
        ao.ad.bronze(this.echo, "secondary=", sb2);
        ao.ad.bronze(this.foxtrot, "onSecondary=", sb2);
        ao.ad.bronze(this.golf, "secondaryContainer=", sb2);
        ao.ad.bronze(this.hotel, "onSecondaryContainer=", sb2);
        ao.ad.bronze(this.india, "tertiary=", sb2);
        ao.ad.bronze(this.juliet, "onTertiary=", sb2);
        ao.ad.bronze(this.kilo, "tertiaryContainer=", sb2);
        ao.ad.bronze(this.lima, "onTertiaryContainer=", sb2);
        ao.ad.bronze(this.mike, "background=", sb2);
        ao.ad.bronze(this.november, "onBackground=", sb2);
        ao.ad.bronze(this.oscar, "surface=", sb2);
        ao.ad.bronze(this.papa, "onSurface=", sb2);
        ao.ad.bronze(this.quebec, "surfaceVariant=", sb2);
        ao.ad.bronze(this.romeo, "onSurfaceVariant=", sb2);
        ao.ad.bronze(this.sierra, "surfaceTint=", sb2);
        ao.ad.bronze(this.tango, "inverseSurface=", sb2);
        ao.ad.bronze(this.uniform, "inverseOnSurface=", sb2);
        ao.ad.bronze(this.victor, "error=", sb2);
        ao.ad.bronze(this.whiskey, "onError=", sb2);
        ao.ad.bronze(this.xray, "errorContainer=", sb2);
        ao.ad.bronze(this.yankee, "onErrorContainer=", sb2);
        ao.ad.bronze(this.zulu, "outline=", sb2);
        ao.ad.bronze(this.amber, "outlineVariant=", sb2);
        ao.ad.bronze(this.azure, "scrim=", sb2);
        ao.ad.bronze(this.beige, "surfaceBright=", sb2);
        ao.ad.bronze(this.black, "surfaceDim=", sb2);
        ao.ad.bronze(this.blue, "surfaceContainer=", sb2);
        ao.ad.bronze(this.bronze, "surfaceContainerHigh=", sb2);
        ao.ad.bronze(this.coral, "surfaceContainerHighest=", sb2);
        ao.ad.bronze(this.crimson, "surfaceContainerLow=", sb2);
        ao.ad.bronze(this.cyan, "surfaceContainerLowest=", sb2);
        sb2.append((Object) C0366t.india(this.emerald));
        sb2.append(')');
        return sb2.toString();
    }
}
