APP_ID=dacca7fa-e670-4783-a857-d25d6e3d064d

# Whether SDK logs are enabled or not
LOG_ENABLED=false

# Whether the SDK will collect installed applications data
INSTALLED_APPS_COLLECTION_ENABLED=true
