package je;

import androidx.appcompat.widget.P0;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import kotlin.NoWhenBranchMatchedException;
import kotlin.collections.CollectionsKt__IterablesKt;
import kotlin.jvm.functions.Function0;
import kotlin.jvm.internal.Intrinsics;
import kotlin.jvm.internal.Lambda;
import pe.AbstractC2347w;
import pe.InterfaceC2330f;
import pe.InterfaceC2334j;
import pe.InterfaceC2349y;
import t6.AbstractC3090z2;
import ue.C3158b;
import ue.C3161e;

/* renamed from: je.t, reason: case insensitive filesystem */
/* loaded from: classes2.dex */
public final class C1980t extends Lambda implements Function0 {
    public final /* synthetic */ int alpha;
    public final /* synthetic */ C1986z purple;

    /* JADX WARN: 'super' call moved to the top of the method (can break code semantics) */
    public /* synthetic */ C1980t(C1986z c1986z, int i4) {
        super(0);
        this.alpha = i4;
        this.purple = c1986z;
    }

    @Override // kotlin.jvm.functions.Function0
    public final Object invoke() {
        int collectionSizeOrDefault;
        InterfaceC2330f delta;
        int i4;
        He.a aVar = null;
        C1986z c1986z = this.purple;
        switch (this.alpha) {
            case 0:
                Collection quebec = c1986z.quebec();
                collectionSizeOrDefault = CollectionsKt__IterablesKt.collectionSizeOrDefault(quebec, 10);
                ArrayList arrayList = new ArrayList(collectionSizeOrDefault);
                Iterator it = quebec.iterator();
                while (it.hasNext()) {
                    arrayList.add(new ah(c1986z, (InterfaceC2334j) it.next()));
                }
                return arrayList;
            case 1:
                return c1986z.tango(c1986z.getDescriptor().oscar().olive(), 1);
            case 2:
                Xe.n lime = c1986z.getDescriptor().lime();
                Intrinsics.delta(lime, "descriptor.staticScope");
                return c1986z.tango(lime, 1);
            case 3:
                int i5 = C1986z.silver;
                Ne.b azure = c1986z.azure();
                C1983w c1983w = (C1983w) c1986z.red.invoke();
                c1983w.getClass();
                ge.v vVar = ac.bravo[0];
                Object invoke = c1983w.alpha.invoke();
                Intrinsics.delta(invoke, "<get-moduleData>(...)");
                boolean z2 = azure.charlie;
                B9.K k6 = ((C3161e) invoke).alpha;
                if (z2) {
                    delta = k6.bravo(azure);
                } else {
                    delta = AbstractC2347w.delta((InterfaceC2349y) k6.bravo, azure);
                }
                if (delta == null) {
                    Class cls = c1986z.purple;
                    C3158b alpha = AbstractC3090z2.alpha(cls);
                    if (alpha != null) {
                        aVar = (He.a) alpha.bravo.delta;
                    }
                    if (aVar == null) {
                        i4 = -1;
                    } else {
                        i4 = AbstractC1984x.$EnumSwitchMapping$0[aVar.ordinal()];
                    }
                    switch (i4) {
                        case -1:
                        case 6:
                            throw new Q(P0.blue(cls, "Unresolved class: "));
                        case 0:
                        default:
                            throw new NoWhenBranchMatchedException();
                        case 1:
                        case 2:
                        case 3:
                            throw new UnsupportedOperationException(P0.blue(cls, "Packages and file facades are not yet supported in Kotlin reflection. Meanwhile please use Java reflection to inspect this class: "));
                        case 4:
                            throw new UnsupportedOperationException(P0.blue(cls, "This class is an internal synthetic class generated by the Kotlin compiler, such as an anonymous class for a lambda, a SAM wrapper, a callable reference, etc. It's not a Kotlin class or interface, so the reflection library has no idea what declarations it has. Please use Java reflection to inspect this class: "));
                        case 5:
                            throw new Q("Unknown class: " + cls + " (kind = " + aVar + ')');
                    }
                }
                return delta;
            case 4:
                return c1986z.tango(c1986z.getDescriptor().oscar().olive(), 2);
            case 5:
                Xe.n lime2 = c1986z.getDescriptor().lime();
                Intrinsics.delta(lime2, "descriptor.staticScope");
                return c1986z.tango(lime2, 2);
            case 6:
                if (c1986z.purple.isAnonymousClass()) {
                    return null;
                }
                Ne.b azure2 = c1986z.azure();
                if (azure2.charlie) {
                    return null;
                }
                return azure2.bravo().bravo();
            default:
                return new C1983w(c1986z);
        }
    }
}
